"""full baseline schema

Revision ID: 3f05d2a4945b
Revises: 
Create Date: 2026-06-29 13:58:21.836561
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '3f05d2a4945b'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_snapshots_snapshot_date'), 'daily_snapshots', ['snapshot_date'], unique=True)
    op.create_table('run_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('detail', sa.String(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_logs_created_at'), 'run_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_run_logs_job'), 'run_logs', ['job'], unique=False)
    op.create_index(op.f('ix_run_logs_status'), 'run_logs', ['status'], unique=False)
    op.create_table('scoring_profile',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('keywords_positive', sa.JSON(), nullable=False),
    sa.Column('keywords_negative', sa.JSON(), nullable=False),
    sa.Column('cpv_preferred', sa.JSON(), nullable=False),
    sa.Column('cpv_excluded', sa.JSON(), nullable=False),
    sa.Column('areas', sa.JSON(), nullable=False),
    sa.Column('team', sa.JSON(), nullable=False),
    sa.Column('project_months', sa.Integer(), nullable=False),
    sa.Column('hourly_rate', sa.Float(), nullable=False),
    sa.Column('margin', sa.Float(), nullable=False),
    sa.Column('go_threshold', sa.Integer(), nullable=False),
    sa.Column('revisar_threshold', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('cpv', sa.JSON(), nullable=False),
    sa.Column('buyer', sa.String(), nullable=True),
    sa.Column('budget_amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('duplicate_of', sa.String(), nullable=True),
    sa.Column('document_text', sa.String(), nullable=True),
    sa.Column('document_extracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_tender_source')
    )
    op.create_index(op.f('ix_tenders_duplicate_of'), 'tenders', ['duplicate_of'], unique=False)
    op.create_index(op.f('ix_tenders_source'), 'tenders', ['source'], unique=False)
    op.create_index(op.f('ix_tenders_source_id'), 'tenders', ['source_id'], unique=False)
    op.create_index(op.f('ix_tenders_status'), 'tenders', ['status'], unique=False)
    op.create_table('generated_documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tender_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('generated_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_documents_kind'), 'generated_documents', ['kind'], unique=False)
    op.create_index(op.f('ix_generated_documents_tender_id'), 'generated_documents', ['tender_id'], unique=False)
    op.create_table('tender_actions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tender_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tender_actions_action'), 'tender_actions', ['action'], unique=False)
    op.create_index(op.f('ix_tender_actions_tender_id'), 'tender_actions', ['tender_id'], unique=False)
    op.create_table('tender_decisions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tender_id', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.Column('final_score', sa.Integer(), nullable=True),
    sa.Column('awarded_company', sa.String(), nullable=True),
    sa.Column('awarded_amount', sa.Float(), nullable=True),
    sa.Column('bid_amount', sa.Float(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tender_decisions_decision'), 'tender_decisions', ['decision'], unique=False)
    op.create_index(op.f('ix_tender_decisions_tender_id'), 'tender_decisions', ['tender_id'], unique=False)
    op.create_table('tender_documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tender_id', sa.String(), nullable=False),
    sa.Column('folder', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tender_documents_tender_id'), 'tender_documents', ['tender_id'], unique=False)
    op.create_table('tender_notes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tender_id', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tender_notes_tender_id'), 'tender_notes', ['tender_id'], unique=False)
    op.create_table('tender_scores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tender_id', sa.String(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=False),
    sa.Column('recommendation', sa.String(), nullable=False),
    sa.Column('hard_rules', sa.JSON(), nullable=False),
    sa.Column('factors', sa.JSON(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tender_scores_recommendation'), 'tender_scores', ['recommendation'], unique=False)
    op.create_index(op.f('ix_tender_scores_tender_id'), 'tender_scores', ['tender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tender_scores_tender_id'), table_name='tender_scores')
    op.drop_index(op.f('ix_tender_scores_recommendation'), table_name='tender_scores')
    op.drop_table('tender_scores')
    op.drop_index(op.f('ix_tender_notes_tender_id'), table_name='tender_notes')
    op.drop_table('tender_notes')
    op.drop_index(op.f('ix_tender_documents_tender_id'), table_name='tender_documents')
    op.drop_table('tender_documents')
    op.drop_index(op.f('ix_tender_decisions_tender_id'), table_name='tender_decisions')
    op.drop_index(op.f('ix_tender_decisions_decision'), table_name='tender_decisions')
    op.drop_table('tender_decisions')
    op.drop_index(op.f('ix_tender_actions_tender_id'), table_name='tender_actions')
    op.drop_index(op.f('ix_tender_actions_action'), table_name='tender_actions')
    op.drop_table('tender_actions')
    op.drop_index(op.f('ix_generated_documents_tender_id'), table_name='generated_documents')
    op.drop_index(op.f('ix_generated_documents_kind'), table_name='generated_documents')
    op.drop_table('generated_documents')
    op.drop_index(op.f('ix_tenders_status'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_source_id'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_source'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_duplicate_of'), table_name='tenders')
    op.drop_table('tenders')
    op.drop_table('scoring_profile')
    op.drop_index(op.f('ix_run_logs_status'), table_name='run_logs')
    op.drop_index(op.f('ix_run_logs_job'), table_name='run_logs')
    op.drop_index(op.f('ix_run_logs_created_at'), table_name='run_logs')
    op.drop_table('run_logs')
    op.drop_index(op.f('ix_daily_snapshots_snapshot_date'), table_name='daily_snapshots')
    op.drop_table('daily_snapshots')
    # ### end Alembic commands ###
